# Generated by Django 5.2.15 on 2026-07-07 10:04

import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_teamchannel_teammessage_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=projects.models.chat_attachment_upload_path, verbose_name='Fichier')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.teammessage')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
