# Generated by Django 5.2.15 on 2026-07-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_teammessageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terminé le'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Actif'), ('COMPLETED', 'Terminé')], default='ACTIVE', max_length=12, verbose_name='Statut'),
        ),
    ]
