# Generated by Django 5.2.15 on 2026-07-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('MEMBER', 'Membre'), ('COLLABORATOR', 'Collaborateur'), ('MANAGER', 'Responsable hierarchique'), ('BUSINESS_OWNER', 'Responsable metier'), ('ACCESS_ADMIN', 'Administrateur habilitations'), ('HR', 'RH'), ('AUDITOR', 'Auditeur'), ('SYSTEM_ADMIN', 'Administrateur systeme')], default='MEMBER', max_length=30, verbose_name='Rôle'),
        ),
    ]
