# Generated by Django 5.2.15 on 2026-07-12 15:36

import django.db.models.deletion
from django.db import migrations, models


ROLE_DETAILS = {
    "ADMIN": ("Administrateur", "Gestion complète de l'application et des utilisateurs."),
    "MEMBER": ("Membre", "Utilisateur opérationnel du tableau des tâches."),
    "COLLABORATOR": ("Collaborateur", "Crée ses demandes et suit ses habilitations."),
    "MANAGER": ("Responsable hiérarchique", "Valide les demandes de son équipe."),
    "BUSINESS_OWNER": ("Responsable métier", "Donne l'avis métier sur les habilitations sensibles."),
    "ACCESS_ADMIN": ("Administrateur habilitations", "Gère le catalogue et les accès accordés."),
    "HR": ("RH", "Gère les mouvements RH et les revues d'accès."),
    "AUDITOR": ("Auditeur", "Consulte l'historique et les traces d'audit."),
    "SYSTEM_ADMIN": ("Administrateur système", "Accès système complet à tous les modules."),
}


def create_system_roles(apps, schema_editor):
    AppRole = apps.get_model("accounts", "AppRole")
    User = apps.get_model("accounts", "User")
    roles = {}
    for key, (name, description) in ROLE_DETAILS.items():
        roles[key], _ = AppRole.objects.get_or_create(
            system_key=key,
            defaults={"name": name, "description": description, "is_system": True},
        )
    for user in User.objects.all().iterator():
        role = roles.get(user.role)
        if role:
            user.custom_role_id = role.pk
            user.save(update_fields=["custom_role"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nom du rôle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('system_key', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('is_system', models.BooleanField(default=False, verbose_name='Rôle système')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='taskflow_roles', to='auth.permission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.approle', verbose_name='Rôle et permissions'),
        ),
        migrations.RunPython(create_system_roles, migrations.RunPython.noop),
    ]
