# Generated by Django 5.2.15 on 2026-07-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_app_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='approle',
            name='permissions_initialized',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
