# Generated by Django 5.2.15 on 2026-07-08 23:06

import django.db.models.deletion
import documents.models
from pathlib import Path
from django.conf import settings
from django.db import migrations, models


def index_existing_files(apps, schema_editor):
    Document = apps.get_model("documents", "Document")
    DocumentHistory = apps.get_model("documents", "DocumentHistory")
    TaskAttachment = apps.get_model("tasks", "Attachment")
    ChatAttachment = apps.get_model("chat", "ChatMessageAttachment")
    LegacyChatAttachment = apps.get_model(
        "projects", "TeamMessageAttachment"
    )
    HabilitationRequest = apps.get_model(
        "access_control", "HabilitationRequest"
    )

    def create_document(
        *,
        source_module,
        source_type,
        source_id,
        file_field,
        original_filename,
        linked_item_label,
        uploaded_by_id=None,
        service="",
        created_at=None,
    ):
        if not file_field:
            return
        filename = original_filename or Path(file_field.name).name
        try:
            file_size = file_field.size
        except (FileNotFoundError, OSError, ValueError):
            file_size = 0
        document = Document.objects.create(
            title=filename,
            original_filename=filename,
            file=file_field.name,
            file_type=Path(filename).suffix.lower().lstrip(".").upper()
            or "FILE",
            file_size=file_size,
            category="ATTACHMENT",
            source_module=source_module,
            source_type=source_type,
            source_id=str(source_id),
            linked_item_label=linked_item_label,
            uploaded_by_id=uploaded_by_id,
            service=service,
        )
        if created_at:
            Document.objects.filter(pk=document.pk).update(created_at=created_at)
        DocumentHistory.objects.create(
            document=document,
            document_title=document.title,
            user_id=uploaded_by_id,
            action="CREATED",
            source_module=source_module,
            details="Indexe depuis le module source.",
        )

    for attachment in TaskAttachment.objects.select_related(
        "task", "task__project"
    ):
        create_document(
            source_module="task",
            source_type="tasks.Attachment",
            source_id=attachment.pk,
            file_field=attachment.file,
            original_filename=attachment.original_name,
            linked_item_label=attachment.task.title,
            uploaded_by_id=attachment.uploaded_by_id,
            service=(
                attachment.task.project.name
                if attachment.task.project_id
                else ""
            ),
            created_at=attachment.uploaded_at,
        )

    for attachment in ChatAttachment.objects.select_related(
        "message__channel", "message__channel__project"
    ):
        create_document(
            source_module="chat",
            source_type="chat.ChatMessageAttachment",
            source_id=attachment.pk,
            file_field=attachment.file,
            original_filename=attachment.original_name,
            linked_item_label=attachment.message.channel.name,
            uploaded_by_id=attachment.uploaded_by_id,
            service=(
                attachment.message.channel.project.name
                if attachment.message.channel.project_id
                else ""
            ),
            created_at=attachment.created_at,
        )

    for attachment in LegacyChatAttachment.objects.select_related(
        "message__channel", "message__author"
    ):
        create_document(
            source_module="chat",
            source_type="projects.TeamMessageAttachment",
            source_id=attachment.pk,
            file_field=attachment.file,
            original_filename=attachment.original_name,
            linked_item_label=(
                attachment.message.channel.name
                if attachment.message.channel_id
                else "Chat equipe"
            ),
            uploaded_by_id=attachment.message.author_id,
            created_at=attachment.uploaded_at,
        )

    for access_request in HabilitationRequest.objects.select_related(
        "requester", "habilitation", "project"
    ).exclude(attachment=""):
        create_document(
            source_module="habilitation_request",
            source_type="access_control.HabilitationRequest",
            source_id=access_request.pk,
            file_field=access_request.attachment,
            original_filename=Path(access_request.attachment.name).name,
            linked_item_label=(
                f"{access_request.reference} - "
                f"{access_request.habilitation.application}"
            ),
            uploaded_by_id=access_request.requester_id,
            service=(
                access_request.project.name
                if access_request.project_id
                else ""
            ),
            created_at=access_request.created_at,
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("access_control", "0009_move_urgency_to_request"),
        ("chat", "0001_initial"),
        ("projects", "0003_teammessageattachment"),
        ("tasks", "0004_task_habilitation_request"),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('file_type', models.CharField(blank=True, max_length=40)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('category', models.CharField(choices=[('REPORT', 'Rapport'), ('PROCEDURE', 'Procedure'), ('TEMPLATE', 'Modele'), ('FORM', 'Formulaire'), ('CHECKLIST', 'Checklist'), ('ATTACHMENT', 'Piece jointe'), ('OTHER', 'Autre')], default='OTHER', max_length=30)),
                ('source_module', models.CharField(choices=[('manual', 'Ajout manuel'), ('task', 'Tache'), ('project', 'Projet'), ('chat', 'Chat equipe'), ('habilitation_request', "Demande d'habilitation"), ('validation', 'Validation'), ('hr_movement', 'Mouvement RH'), ('user', 'Utilisateur')], default='manual', max_length=40)),
                ('source_type', models.CharField(blank=True, max_length=120)),
                ('source_id', models.CharField(blank=True, max_length=80)),
                ('linked_item_label', models.CharField(blank=True, max_length=255)),
                ('service', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('ARCHIVED', 'Archive')], default='ACTIVE', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('CREATED', 'Ajout document'), ('DOWNLOADED', 'Telechargement'), ('OPENED', 'Ouverture'), ('UPDATED', 'Modification'), ('ARCHIVED', 'Archivage'), ('RESTORED', 'Restauration'), ('DELETED', 'Suppression')], max_length=20)),
                ('source_module', models.CharField(blank=True, choices=[('manual', 'Ajout manuel'), ('task', 'Tache'), ('project', 'Projet'), ('chat', 'Chat equipe'), ('habilitation_request', "Demande d'habilitation"), ('validation', 'Validation'), ('hr_movement', 'Mouvement RH'), ('user', 'Utilisateur')], max_length=40)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='documents.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['source_module', 'source_type', 'source_id'], name='documents_d_source__7cedb6_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category', 'is_archived'], name='documents_d_categor_603a74_idx'),
        ),
        migrations.RunPython(index_existing_files, migrations.RunPython.noop),
    ]
