# Generated by Django 5.2.15 on 2026-07-07 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
        ('tasks', '0003_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='habilitation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='access_control.habilitationrequest', verbose_name="Demande d'habilitation"),
        ),
    ]
