# Generated by Django 5.2.15 on 2026-07-11 23:57

from django.conf import settings
from django.db import migrations, models


def copy_legacy_assignees(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    through = Task.assignees.through
    through.objects.bulk_create(
        [through(task_id=task.pk, user_id=task.assigned_to_id)
         for task in Task.objects.exclude(assigned_to_id=None)],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_status_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs assignés'),
        ),
        migrations.RunPython(copy_legacy_assignees, migrations.RunPython.noop),
    ]
