# Generated by Django 5.2.15 on 2026-07-07 18:41

import access_control.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_teammessageattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(blank=True, max_length=80)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('ARRIVAL', "Arrivee d'un salarie"), ('INTERNAL_MOVE', 'Mutation interne'), ('ROLE_CHANGE', 'Changement de fonction'), ('DEPARTURE', 'Depart'), ('SUSPENSION', 'Suspension temporaire')], max_length=30)),
                ('old_department', models.CharField(blank=True, max_length=120)),
                ('new_department', models.CharField(blank=True, max_length=120)),
                ('old_position', models.CharField(blank=True, max_length=120)),
                ('new_position', models.CharField(blank=True, max_length=120)),
                ('effective_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'A traiter'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Traite')], default='PENDING', max_length=20)),
                ('justification', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Habilitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('type', models.CharField(choices=[('APPLICATION', 'Application'), ('DATABASE', 'Base de donnees'), ('NETWORK', 'Reseau'), ('PHYSICAL', 'Physique'), ('EQUIPMENT', 'Equipement'), ('INTERNAL_SYSTEM', 'Systeme interne')], default='APPLICATION', max_length=30)),
                ('criticality', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Elevee'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=20)),
                ('validity_duration_days', models.PositiveIntegerField(default=365)),
                ('procedure', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_habilitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HabilitationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('access_type', models.CharField(choices=[('READ', 'Lecture'), ('WRITE', 'Ecriture'), ('ADMIN', 'Administration'), ('TEMPORARY', 'Temporaire')], default='READ', max_length=20)),
                ('justification', models.TextField()),
                ('requested_start_date', models.DateField()),
                ('requested_duration_days', models.PositiveIntegerField(default=365)),
                ('requested_end_date', models.DateField()),
                ('attachment', models.FileField(blank=True, upload_to=access_control.models.request_attachment_upload_path)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumise'), ('PENDING_MANAGER', 'En attente manager'), ('PENDING_BUSINESS', 'En attente responsable metier'), ('PENDING_ADMIN', 'En attente administrateur'), ('INFO_REQUESTED', "En attente d'information"), ('GRANTED', 'Accordee'), ('REJECTED', 'Refusee'), ('EXPIRED', 'Expiree'), ('REVOKED', 'Revoquee')], default='DRAFT', max_length=30)),
                ('current_step', models.CharField(default='Brouillon', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habilitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='access_control.habilitation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habilitation_requests', to='projects.project')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habilitation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabilitationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRES_SOON', 'Expire bientot'), ('EXPIRED', 'Expiree'), ('REVOKED', 'Revoquee'), ('SUSPENDED', 'Suspendue')], default='ACTIVE', max_length=20)),
                ('revoked_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_habilitations', to=settings.AUTH_USER_MODEL)),
                ('habilitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='access_control.habilitation')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_habilitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilitation_assignments', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='access_control.habilitationrequest')),
            ],
            options={
                'ordering': ['end_date'],
            },
        ),
        migrations.CreateModel(
            name='HabilitationRequestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('decision', models.CharField(choices=[('NONE', '-'), ('APPROVE', 'Approuver'), ('REJECT', 'Refuser'), ('REQUEST_INFO', 'Demander information'), ('GRANT', 'Attribuer')], default='NONE', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('WAITING', 'A venir'), ('PENDING', 'En attente'), ('APPROVED', 'Approuvee'), ('REJECTED', 'Refusee'), ('INFO_REQUESTED', 'Information demandee'), ('SKIPPED', 'Ignoree')], default='PENDING', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habilitation_steps', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='access_control.habilitationrequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
