# Generated by Django 5.2.15 on 2026-07-07 18:42

from datetime import date, timedelta

from django.db import migrations


DEFAULT_HABILITATIONS = [
    ("SAP001", "Acces SAP Achat", "APPLICATION", "CRITICAL", 365),
    ("ORA002", "Acces Oracle Production", "DATABASE", "CRITICAL", 180),
    ("NET003", "VPN Entreprise", "NETWORK", "HIGH", 365),
    ("BAD004", "Badge Zone sensible", "PHYSICAL", "CRITICAL", 90),
]


def seed_defaults(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Habilitation = apps.get_model("access_control", "Habilitation")
    HabilitationRequest = apps.get_model("access_control", "HabilitationRequest")
    HabilitationAssignment = apps.get_model("access_control", "HabilitationAssignment")
    AuditLog = apps.get_model("access_control", "AuditLog")

    responsible = User.objects.filter(is_active=True).order_by("name").first()
    created = []
    for code, name, type_value, criticality, duration in DEFAULT_HABILITATIONS:
        habilitation, was_created = Habilitation.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "type": type_value,
                "criticality": criticality,
                "validity_duration_days": duration,
                "responsible": responsible,
                "procedure": "Procedure interne a renseigner.",
                "description": f"Habilitation exemple : {name}.",
                "status": "ACTIVE",
            },
        )
        if was_created:
            created.append(habilitation)

    if responsible and created:
        start = date.today()
        request_item, _ = HabilitationRequest.objects.get_or_create(
            reference=f"HAB-{start.year}-0001",
            defaults={
                "requester": responsible,
                "habilitation": created[0],
                "access_type": "READ",
                "justification": "Exemple de demande d'habilitation initiale.",
                "requested_start_date": start,
                "requested_duration_days": created[0].validity_duration_days,
                "requested_end_date": start + timedelta(days=created[0].validity_duration_days),
                "status": "GRANTED",
                "current_step": "Acces attribue",
            },
        )
        HabilitationAssignment.objects.get_or_create(
            user=responsible,
            habilitation=created[0],
            request=request_item,
            defaults={
                "start_date": start,
                "end_date": start + timedelta(days=created[0].validity_duration_days),
                "status": "ACTIVE",
                "granted_by": responsible,
            },
        )
        AuditLog.objects.get_or_create(
            action="Initialisation catalogue",
            entity_type="Habilitation",
            entity_id=created[0].code,
            defaults={
                "user": responsible,
                "new_value": "Donnees exemples creees",
            },
        )


def remove_defaults(apps, schema_editor):
    Habilitation = apps.get_model("access_control", "Habilitation")
    HabilitationRequest = apps.get_model("access_control", "HabilitationRequest")
    HabilitationAssignment = apps.get_model("access_control", "HabilitationAssignment")
    codes = [item[0] for item in DEFAULT_HABILITATIONS]
    HabilitationAssignment.objects.filter(habilitation__code__in=codes).delete()
    HabilitationRequest.objects.filter(habilitation__code__in=codes).delete()
    Habilitation.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_defaults, remove_defaults),
    ]
