# Generated by Django 5.2.15 on 2026-07-08 16:55

import django.utils.timezone
from datetime import timedelta
from django.db import migrations, models


def convert_durations_to_dates(apps, schema_editor):
    Habilitation = apps.get_model("access_control", "Habilitation")
    for item in Habilitation.objects.all():
        if item.validity_duration_days is not None:
            item.validity_end_date = item.validity_start_date + timedelta(
                days=item.validity_duration_days
            )
            item.save(update_fields=["validity_end_date"])


def restore_missing_durations(apps, schema_editor):
    Habilitation = apps.get_model("access_control", "Habilitation")
    Habilitation.objects.filter(validity_duration_days__isnull=True).update(
        validity_duration_days=365
    )


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_application_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilitation',
            name='validity_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habilitation',
            name='validity_start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='habilitation',
            name='validity_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(convert_durations_to_dates, restore_missing_durations),
    ]
