# Generated by Django 5.2.15 on 2026-07-08 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0005_habilitation_validity_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habilitation',
            name='validity_duration_days',
        ),
        migrations.RemoveField(
            model_name='habilitation',
            name='validity_end_date',
        ),
        migrations.RemoveField(
            model_name='habilitation',
            name='validity_start_date',
        ),
    ]
