# Generated by Django 5.2.15 on 2026-07-08 17:20

import django.db.models.deletion
from django.db import migrations, models


ACCESS_TYPE_LABELS = {
    "READ": "Lecture",
    "WRITE": "Ecriture",
    "READ_WRITE": "Lecture / ecriture",
    "ADMINISTRATION": "Administration",
    "REMOTE": "Distant",
    "TEMPORARY": "Temporaire",
    "PHYSICAL": "Physique",
}


def move_access_types_to_items(apps, schema_editor):
    Habilitation = apps.get_model("access_control", "Habilitation")
    HabilitationAccessType = apps.get_model(
        "access_control", "HabilitationAccessType"
    )
    for application in Habilitation.objects.all():
        HabilitationAccessType.objects.create(
            application=application,
            name=ACCESS_TYPE_LABELS.get(
                application.access_type,
                application.access_type,
            ),
        )


def restore_primary_access_type(apps, schema_editor):
    Habilitation = apps.get_model("access_control", "Habilitation")
    reverse_labels = {label: value for value, label in ACCESS_TYPE_LABELS.items()}
    for application in Habilitation.objects.prefetch_related("access_types"):
        first_type = application.access_types.order_by("position", "id").first()
        application.access_type = (
            reverse_labels.get(first_type.name, "READ") if first_type else "READ"
        )
        application.save(update_fields=["access_type"])


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0006_remove_habilitation_validity_duration_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabilitationAccessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('position', models.PositiveIntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_types', to='access_control.habilitation')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('application', 'name'), name='unique_access_type_per_application')],
            },
        ),
        migrations.RunPython(
            move_access_types_to_items,
            restore_primary_access_type,
        ),
        migrations.RemoveField(
            model_name='habilitation',
            name='access_type',
        ),
    ]
